### ISSUE TITLE
Splitting packages

### ISSUE THREAD

**Issue by jklmnn** [Componolit/AZ3#33]
I would suggest to split the Z3 package into multiple ones. As a quick idea I'd propose the following structure:
 - `Z3`
   - `Z3.Solver`
   - `Z3.Optimize`

The reason for that is that our current spec has over 600 lines and the body has over 1300. It becomes more and more difficult to make changes, especially if they apply to both the public and private part of the spec since locating the code that needs to be modified becomes more tedious.

**Comment by senier** [comment]
Archiving repository.
