### ISSUE TITLE
Moving contexts

### ISSUE THREAD

**Issue by jklmnn** [Componolit/AZ3#39]
Each context and all its content must be kept in a single thread. To split a set of expressions into multiple threads they have to be moved to the respective context of the thread. This can be done by [Z3_translate](https://z3prover.github.io/api/html/group__capi.html#ga9034ab0dbfff188e15a02421488ea8cf).

**Comment by senier** [comment]
Archiving repository.

**Comment by senier** [comment]
Archiving repository.

**Comment by senier** [comment]
Archiving repository.
