### ISSUE TITLE
Failing comparisons

### ISSUE THREAD

**Issue by jklmnn** [Componolit/AZ3#7]
In other projects some comparisons, even between simple expressions fail even if those expressions are equal. This happens differently in different Z3 versions.

For Z3 4.4.1 - 4.8.4: 6cadebf016729655fbc4d9434691eb4d91d3dc7e
For Z3 4.8.7+: 6e359057e0fc09afbb364c78b8744d3f20c6ad81

**Comment by senier** [comment]
Archiving repository.
